services:
  - type: web
    name: car11-backend
    env: python
    rootDir: car11-backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.main:app"
    healthCheckPath: /healthz
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: car11-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://car11-frontend.onrender.com   # after first deploy, update to the actual URL if different

  - type: static
    name: car11-frontend
    rootDir: car11-frontend
    envVars:
      - key: VITE_API_URL
        value: https://car11-backend.onrender.com
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    plan: free

databases:
  - name: car11-db
    plan: free
