services:
  - type: web
    name: car11-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.main:app"
    plan: free
    envVars:
      - key: FRONTEND_URL
        value: https://your-frontend.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: car11-db
          property: connectionString

databases:
  - name: car11-db
    databaseName: car11
    user: car11user
    plan: free

